### ISSUE TITLE
Create routing for screens

### ISSUE THREAD

**Issue by RawiriHohepa** [SE750-DART/nerds-oppose-society#12]
-  [x] Decide on what pages are needed
-  [x] Create routes to navigate between the various pages of the frontend.

**Additional Notes**
See the [figma design](https://www.figma.com/file/7sUdrcJ9FfW7r2gY1UUb07/750---Nerds-Oppose-Society?node-id=0%3A1) for the designs for most of the game functionality

**Comment by taitfuller** [comment]
The actual Routing itself is interesting. I feel like we don't need to care about updating the URL with different screens and that something like [<MemoryRouter>](https://reactrouter.com/web/api/MemoryRouter) could do the trick for us 🤔

**Comment by RawiriHohepa** [comment]
Routing flow pseudocode:
```
if /home
	null
else if /game_code
	GET /game/validate
	if valid
		if user_id (localstorage)
			connect(game_code(URL), user_id(localstorage))
			memoryrouter [listen]
		else 
			memoryrouter /nickname
			POST /user/create
			setlocalstorage(user_id)
			connect(game_code(URL), user_id(res))
	else
		browserrouter /home (or whatever error handling)
		
```
