### ISSUE TITLE
Create frontend components for the whole game

### ISSUE THREAD

**Issue by dikunong** [SE750-DART/nerds-oppose-society#33]
Once the barebones lobby is complete for Sprint 1, we need to construct the remaining custom UI components that will be used through the application for the rest of the game screens.

For Sprint 2:

-  [x] Dropdown
-  [x] PunchlineCard
-  [x] ProgressBar
-  [ ] RoundTimer
-  [ ] Podium

TBD:

-  [ ] Checkbox

**Additional notes**

[Figma](https://www.figma.com/file/7sUdrcJ9FfW7r2gY1UUb07/750---Nerds-Oppose-Society?node-id=0%3A1)

**Comment by RawiriHohepa** [comment]
I'll work on ProgressBar
