### ISSUE TITLE
Not persisting settings in DB

### ISSUE THREAD

**Issue by taitfuller** [SE750-DART/nerds-oppose-society#73]
Whenever users update settings in the frontend and reload these changes are not persisted when initialised from the DB. It appears there is either an issue with the settings handler or service that is not saving these updates to the DB to be retrieved when a user reloads

**Comment by Alxjlv** [comment]
So the issue is that when a user reconnects they won't pull the settings again? Or the host when making the game doesn't persist the settings to the backend?
