### ISSUE TITLE
Validate game settings in Mongoose

### ISSUE THREAD

**Issue by Alxjlv** [SE750-DART/nerds-oppose-society#93]
Currently we don't validate the upper limit for max players in a lobby

**Comment by taitfuller** [comment]
We can use Mongoose Validation on the setting schema's as shown here: [https://mongoosejs.com/docs/validation.html](https://mongoosejs.com/docs/validation.html)

We'd be looking at the following
- maxPlayers: Min: 3, Max: 40
- roundLimit: Min: 1

**Comment by taitfuller** [comment]
Will be good to define a constant for the MinPlayers too as this will be needed by the handlers for #96
